// AUTO GENERATED BY JNIGEN 0.15.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String, bool, double, int;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

/// from: `dev.roszkowski.screen_brightness_monitor.BrightnessCallback`
class BrightnessCallback extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<BrightnessCallback> $type;

  @jni$_.internal
  BrightnessCallback.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/roszkowski/screen_brightness_monitor/BrightnessCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<BrightnessCallback?> nullableType =
      $BrightnessCallback$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<BrightnessCallback> type =
      $BrightnessCallback$Type$();
  static final _id_onBrightnessChanged = _class.instanceMethodId(
    r'onBrightnessChanged',
    r'(I)V',
  );

  static final _onBrightnessChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
            )
          >();

  /// from: `public fun onBrightnessChanged(brightness: kotlin.Int): kotlin.Unit`
  void onBrightnessChanged(int i) {
    _onBrightnessChanged(
      reference.pointer,
      _id_onBrightnessChanged as jni$_.JMethodIDPtr,
      i,
    ).check();
  }

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<int, $BrightnessCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onBrightnessChanged(I)V') {
        _$impls[$p]!.onBrightnessChanged(
          $a![0]!
              .as(const jni$_.$JInteger$Type$(), releaseOriginal: true)
              .intValue(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $BrightnessCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'dev.roszkowski.screen_brightness_monitor.BrightnessCallback',
      $p,
      _$invokePointer,
      [if ($impl.onBrightnessChanged$async) r'onBrightnessChanged(I)V'],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory BrightnessCallback.implement($BrightnessCallback $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return BrightnessCallback.fromReference($i.implementReference());
  }
}

abstract base mixin class $BrightnessCallback {
  factory $BrightnessCallback({
    required void Function(int i) onBrightnessChanged,
    bool onBrightnessChanged$async,
  }) = _$BrightnessCallback;

  void onBrightnessChanged(int i);
  bool get onBrightnessChanged$async => false;
}

final class _$BrightnessCallback with $BrightnessCallback {
  _$BrightnessCallback({
    required void Function(int i) onBrightnessChanged,
    this.onBrightnessChanged$async = false,
  }) : _onBrightnessChanged = onBrightnessChanged;

  final void Function(int i) _onBrightnessChanged;
  final bool onBrightnessChanged$async;

  void onBrightnessChanged(int i) {
    return _onBrightnessChanged(i);
  }
}

final class $BrightnessCallback$NullableType$
    extends jni$_.JType<BrightnessCallback?> {
  @jni$_.internal
  const $BrightnessCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/roszkowski/screen_brightness_monitor/BrightnessCallback;';

  @jni$_.internal
  @core$_.override
  BrightnessCallback? fromReference(jni$_.JReference reference) =>
      reference.isNull ? null : BrightnessCallback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<BrightnessCallback?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($BrightnessCallback$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($BrightnessCallback$NullableType$) &&
        other is $BrightnessCallback$NullableType$;
  }
}

final class $BrightnessCallback$Type$ extends jni$_.JType<BrightnessCallback> {
  @jni$_.internal
  const $BrightnessCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/roszkowski/screen_brightness_monitor/BrightnessCallback;';

  @jni$_.internal
  @core$_.override
  BrightnessCallback fromReference(jni$_.JReference reference) =>
      BrightnessCallback.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<BrightnessCallback?> get nullableType =>
      const $BrightnessCallback$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($BrightnessCallback$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($BrightnessCallback$Type$) &&
        other is $BrightnessCallback$Type$;
  }
}

/// from: `dev.roszkowski.screen_brightness_monitor.ScreenBrightnessMonitor`
class ScreenBrightnessMonitor extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JType<ScreenBrightnessMonitor> $type;

  @jni$_.internal
  ScreenBrightnessMonitor.fromReference(jni$_.JReference reference)
    : $type = type,
      super.fromReference(reference);

  static final _class = jni$_.JClass.forName(
    r'dev/roszkowski/screen_brightness_monitor/ScreenBrightnessMonitor',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ScreenBrightnessMonitor?> nullableType =
      $ScreenBrightnessMonitor$NullableType$();

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<ScreenBrightnessMonitor> type =
      $ScreenBrightnessMonitor$Type$();
  static final _id_new$ = _class.constructorId(r'(Landroid/content/Context;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.content.Context context)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ScreenBrightnessMonitor(jni$_.JObject context) {
    final _$context = context.reference;
    return ScreenBrightnessMonitor.fromReference(
      _new$(
        _class.reference.pointer,
        _id_new$ as jni$_.JMethodIDPtr,
        _$context.pointer,
      ).reference,
    );
  }

  static final _id_getBrightness = _class.instanceMethodId(
    r'getBrightness',
    r'()I',
  );

  static final _getBrightness =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallIntMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final int getBrightness()`
  int getBrightness() {
    return _getBrightness(
      reference.pointer,
      _id_getBrightness as jni$_.JMethodIDPtr,
    ).integer;
  }

  static final _id_startObserving = _class.instanceMethodId(
    r'startObserving',
    r'(Ldev/roszkowski/screen_brightness_monitor/BrightnessCallback;)V',
  );

  static final _startObserving =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun startObserving(callback: dev.roszkowski.screen_brightness_monitor.BrightnessCallback): kotlin.Unit`
  void startObserving(BrightnessCallback brightnessCallback) {
    final _$brightnessCallback = brightnessCallback.reference;
    _startObserving(
      reference.pointer,
      _id_startObserving as jni$_.JMethodIDPtr,
      _$brightnessCallback.pointer,
    ).check();
  }

  static final _id_stopObserving = _class.instanceMethodId(
    r'stopObserving',
    r'()V',
  );

  static final _stopObserving =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun stopObserving(): kotlin.Unit`
  void stopObserving() {
    _stopObserving(
      reference.pointer,
      _id_stopObserving as jni$_.JMethodIDPtr,
    ).check();
  }
}

final class $ScreenBrightnessMonitor$NullableType$
    extends jni$_.JType<ScreenBrightnessMonitor?> {
  @jni$_.internal
  const $ScreenBrightnessMonitor$NullableType$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/roszkowski/screen_brightness_monitor/ScreenBrightnessMonitor;';

  @jni$_.internal
  @core$_.override
  ScreenBrightnessMonitor? fromReference(jni$_.JReference reference) =>
      reference.isNull
      ? null
      : ScreenBrightnessMonitor.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ScreenBrightnessMonitor?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ScreenBrightnessMonitor$NullableType$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ScreenBrightnessMonitor$NullableType$) &&
        other is $ScreenBrightnessMonitor$NullableType$;
  }
}

final class $ScreenBrightnessMonitor$Type$
    extends jni$_.JType<ScreenBrightnessMonitor> {
  @jni$_.internal
  const $ScreenBrightnessMonitor$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Ldev/roszkowski/screen_brightness_monitor/ScreenBrightnessMonitor;';

  @jni$_.internal
  @core$_.override
  ScreenBrightnessMonitor fromReference(jni$_.JReference reference) =>
      ScreenBrightnessMonitor.fromReference(reference);
  @jni$_.internal
  @core$_.override
  jni$_.JType get superType => const jni$_.$JObject$Type$();

  @jni$_.internal
  @core$_.override
  jni$_.JType<ScreenBrightnessMonitor?> get nullableType =>
      const $ScreenBrightnessMonitor$NullableType$();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ScreenBrightnessMonitor$Type$).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ScreenBrightnessMonitor$Type$) &&
        other is $ScreenBrightnessMonitor$Type$;
  }
}
